#define FALSE 0 
#define TRUE 1

//Maths
#define PI 3.14159265
#define TWO_PI 6.28318530

//Raycast
#define TILE_SIZE 64
#define MAP_NUM_ROWS 13
#define MAP_NUM_COLS 20
#define MINIMAP_SCALE_FACTOR 0.2

#define FOV_ANGLE (60 * PI / 180)
#define NUM_RAYS WINDOW_WIDTH

//WINDOWS DEFINE
#define WINDOW_WIDTH (MAP_NUM_COLS * TILE_SIZE)
#define WINDOW_HEIGHT (MAP_NUM_ROWS * TILE_SIZE)

//TEXTURE
#define TEXTURE_WIDTH 64
#define TEXTURE_HEIGHT 64

#define FPS 30
#define FRAME_TIME_LENGTH (1000/FPS)

#define NUM_TEXTURES 8

